### ISSUE TITLE
No module named 'eval_tools'

### ISSUE THREAD

**Issue by souravsanyal06** [Weixy21/BarrierNet#1]
While trying to run the example provided, I am getting error at file eval.py in Line 10 "from eval_tools import utils" which says
ModuleNotFoundError: No module named 'eval_tools'

**Comment by Weixy21** [comment]
Thanks a lot for catching this problem. The module eval_tools was indeed missing. I have uploaded this module. Please let me know if you still have errors while running the example.

**Comment by souravsanyal06** [comment]
Thanks! Can you please point me to the resource where I can get the vista meshes like carpack01 ? That is the next filenotfounderror when running scripts/eval_example.sh

**Comment by Weixy21** [comment]
I have uploaded the carpack01, and it is shared through a google drive. The information can be found in the README page.  The example running code has also updated accordingly. Please let me know if there still any errors. Thanks.
